### PR TITLE
 Integrate next-auth for support of social logins

### PR DESCRIPTION
**Pull request by GloireMutaliko21**
https://github.com/ever-co/ever-teams/issues/187

- [x] Google, Facebook, Twitter and GitHub providers
- [x] Auth Sign In configurations

### CODE REVIEW

**Comment by evereq** [comment]
@GloireMutaliko21 don't forget to rebase this :) As it include a lot of commits not related to this PR in the history...

**Comment by GloireMutaliko21** [comment]
Sir @evereq ! I think we can merge this PR.
Actually, we have the following flow working : 

- The user can choose a social media for signin and be redirected to an OAuth page
- He can choose his account and then be redirected to workspaces list if he was authenticated both with OAuth provider and Gauzy APIs
- After choosing a workspace, redirected to the app home page
- He can also sign out

We do not have yet Adaptor, Think can work on it on next PR related to the issue #1063

**Comment by evereq** [comment]
@GloireMutaliko21 merged with Squash, don't push to this branch anymore, create new one based on develop etc
Also, what will happen if we did not set env vars that needed? Will it keep working or fail!? We need to make sure All those social auth are optional and if env vars not set, it just not render those options for login and only render those that are configured correctly!

**Comment by GloireMutaliko21** [comment]
Sir @evereq right now we need all the configured environment variables... I must be able to make this dynamic to hide options that don't have the necessary configurations. Can I create an issue for this ?

**Comment by evereq** [comment]
> Sir @evereq right now we need all the configured environment variables... I must be able to make this dynamic to hide options that don't have the necessary configurations. Can I create an issue for this ?

Yes and work in NEW branch based on `develop` branch!

**Pull request merged**
