### PR TITLE
2232 feature svgr configuration for web

### PR DESCRIPTION
**Pull request by Anishali2**

### CODE REVIEW

**Comment by Anishali2** [comment]
Sir paradoxe and I worked on same files and I have to take a deep look of her change so that the project didn't break I'll fix these conflicts issues tomorrow

I can create a simple docs folder and readme file of icons-usage. how to use icons accordingly so we can maintain re-usablity

**Comment by evereq** [comment]
@Anishali2 you will have to fix merge issues as seems other devs changed the same files. Let me know when it's done (please do it careful to make sure others changes not get lost)

**Comment by Anishali2** [comment]
> @Anishali2 you will have to fix merge issues as seems other devs changed the same files. Let me know when it's done (please do it careful to make sure others changes not get lost)

I'll fix these carefully Sir don't worry

**Comment by evereq** [comment]
> Sir paradoxe and I worked on same files and I have to take a deep look of her change so that the project didn't break I'll fix these conflicts issues tomorrow
> 
> I can create a simple docs folder and readme file of icons-usage. how to use icons accordingly so we can maintain re-usablity

Yes, please add it to WIKI for now https://github.com/ever-co/ever-teams/wiki, just create new page like "SVG Icons Management" and put there all relevant info

**Comment by Anishali2** [comment]
> > Sir paradoxe and I worked on same files and I have to take a deep look of her change so that the project didn't break I'll fix these conflicts issues tomorrow
> > I can create a simple docs folder and readme file of icons-usage. how to use icons accordingly so we can maintain re-usablity
> 
> Yes, please add it to WIKI for now https://github.com/ever-co/ever-teams/wiki, just create new page like "SVG Icons Management" and put there all relevant info

Sure I'm at office when I'll be free i can do these changes

**Comment by Anishali2** [comment]
Sir I've test icons and fixed if some issues exist also the spell check is checked and I've see every icons in details most of the icons which we can use in future are in there in the project 
I'll create the wiki in next branch because it's already huge files

**Comment by Anishali2** [comment]
[icons-fixes.webm](https://github.com/ever-co/ever-teams/assets/105014311/c09cc8bb-3870-4f33-9bd6-8450a4c5e3f3)

**Comment by Anishali2** [comment]
[icones-fixes-black.webm](https://github.com/ever-co/ever-teams/assets/105014311/b3114df4-525f-4d1a-a345-6718e32bc723)

**Comment by Anishali2** [comment]
image

image

**Comment by Anishali2** [comment]
Sir please try to merge this PR before merging new one because I've worked on almost every file so that chances of having conflicts are high :)

**Pull request merged**
