### PR TITLE
Improve/hamburger menu blur

### PR DESCRIPTION
**Pull request by desperado1802**
#1610
Added blur when Hamburger Menu is opened

Now:
https://github.com/ever-co/ever-teams/assets/124465103/7a719941-0dcb-45d2-8cb5-7fdd1fa72f25

Before:
image

### CODE REVIEW

**Comment by badalkhatri0924** [comment]
> After adding the blur the Hamburger Drawer no longer closes when pressed on blurred area. Didn't add that functionality as there is the "X" icon to close. Let me know if it needs to be closed on blur press, @badalkhatri0924

@evereq

**Comment by evereq** [comment]
@badalkhatri0924 / @desperado1802  I don't think that "X" looks good, let's remove it and just make sure if user click on that blur area, menu close. Also, I would make the menu block itself to use almost all width (i.e. make that area much wider and decrease side of blurred space). I checked other apps and it's usually blurred areas is like 1/5 of screen or even 1/6 of screen width, while menu is large and can display all info easy (e.g. that combobox with team selection).

**Comment by evereq** [comment]
See picture below @badalkhatri0924 / @desperado1802 

image

**Comment by desperado1802** [comment]
Can you check if the width is fine @evereq 
https://github.com/ever-co/ever-teams/assets/124465103/db1a77c6-5a72-44db-b54f-fd3d56537bd3

**Comment by evereq** [comment]
@desperado1802 yes, width is fine now, let me know when it's ready to be merged :)

**Comment by desperado1802** [comment]
> @desperado1802 yes, width is fine now, let me know when it's ready to be merged :)

We can merge @evereq

**Pull request merged**
