### PR TITLE
[Fix]: task status ids are fixed in kanban board

### PR DESCRIPTION
**Pull request by Anishali2**

### CODE REVIEW

**Comment by Anishali2** [comment]
Sir, now you can create a new task on the home page it will show that task in Kanban but it only works with newly created tasks

**Comment by evereq** [comment]
@Anishali2 How can we "fix" existed tasks? Maybe @rahul-rocket can help to create some data migration in Gauzy that goes over all tasks and "fix" they status ID according to status name, is that what we need to see tasks in Kanban?

**Comment by Anishali2** [comment]
Sir, there is only the status name is stored and if the name is not changed then it is possible if the name is changed then it's hard for anyone to figure out which status it is saved before because now there is no status exist

**Comment by rahul-rocket** [comment]
@Anishali2 @evereq Okay. Atleast we can set status ID for those statuses which is not changed yet. 

Note: We need to create migration for this.

**Comment by evereq** [comment]
@rahul-rocket yes, so you mean like iterate over all tasks that exists, see if "statuses" table have same name (for the same tenant / org) as saved in "task" and if yes, set statusId in the task to correct value? You mean migration like that?

**Pull request merged**
