### PR TITLE
Feat/Next-Frontend APIs

### PR DESCRIPTION
**Pull request by paradoxe35**
POST /auth/signin-email-confirm
POST /auth/verify/token
POST /auth/refresh
POST /auth/signin-workspace

### CODE REVIEW

**Comment by paradoxe35** [comment]
These two remaining endpoints:
POST /auth/registry
POST /auth/jwt

And these should be implemented from the Gauzy site (Unless we define some trade-off), 
because /auth/register requires captcha private key and smtp configuration, 
and /auth/jwt needs JWT Private env to generate auth token for Jitsi Meet.

**Comment by paradoxe35** [comment]
I think we can merge if looks good to you
I will commit new fixes on another PR

**Comment by evereq** [comment]
@paradoxe35 any ideas why "build before merge" Github action failing now? Also fix Deepscan and spelling please

**Comment by evereq** [comment]
@paradoxe35 and deepscan / spell??

**Comment by paradoxe35** [comment]
@evereq 

Fixed deepscan but the spell I don't know if warnings comes from my PR

**Comment by paradoxe35** [comment]
And Webapp.io also

**Pull request merged**
