### PR TITLE
[Feat] Soft Daily Plan popup

### PR DESCRIPTION
**Pull request by GedeonTS**
https://github.com/user-attachments/assets/310384c8-4611-4290-b0ce-2b459b9e7d67

### CODE REVIEW

**Comment by evereq** [comment]
@GedeonTS what we are waiting with this PR?

**Comment by GedeonTS** [comment]
> @GedeonTS what we are waiting with this PR?

I had some alignment to do with Gloire, once it is done will be ready to merge quickly

**Comment by evereq** [comment]
@Cedric921 can you check this PR please (and also fix merge conflict carefully)

**Comment by evereq** [comment]
@Cedric921 also please fix any issues quickly yourself (e.g. lots of commented out code), so we don't get into infinite communication loop on this PR please :)

**Comment by evereq** [comment]
@GloireMutaliko21 Actually, maybe even better if you review this PR actually, because I think you worked on the same things in https://github.com/ever-co/ever-teams/issues/2679... 
I don't know how we get so similar tasks https://github.com/ever-co/ever-teams/issues/2680 and https://github.com/ever-co/ever-teams/issues/2679 assigned to different people and also both seems worked on the same!? 

Anyway, @GloireMutaliko21 please check and make sure BOTH 2679 and 2680 issues are resolved in FULL and this PR is clean and can be merged (remove comments, review code etc).

**Comment by GloireMutaliko21** [comment]
> @GloireMutaliko21 Actually, maybe even better if you review this PR actually, because I think you worked on the same things in #2679... I don't know how we get so similar tasks #2680 and #2679 assigned to different people and also both seems worked on the same!?
> 
> Anyway, @GloireMutaliko21 please check and make sure BOTH 2679 and 2680 issues are resolved in FULL and this PR is clean and can be merged (remove comments, review code etc).

Sir @evereq actually we have lots of similar tasks related to this SOFT Daily Plan feature. I worked on it (A kind of v1) and now @CREDO23 is working to finalize it. So I really think for this PR, we can fix merge conflicts first, then try to sync it with what @CREDO23 work on or only close it as it seems not completed all the flows suggested by @KostyaEver 

CC: @KostyaEver, @CREDO23

**Comment by evereq** [comment]
@CREDO23 can you see please what's best to do with this PR? Can we get merge conflicts resolved / fixed etc so it makes sense to merge it? Or better to close it and maybe copy some of code from it to another (new) PR? Please take care about this PR as it stay open in Draft forever :(

**Comment by CREDO23** [comment]
> @CREDO23 can you see please what's best to do with this PR? Can we get merge conflicts resolved / fixed etc so it makes sense to merge it? Or better to close it and maybe copy some of code from it to another (new) PR? Please take care about this PR as it stay open in Draft forever :(
> 
> CC: @Innocent-Akim I think you also worked on some things related? Maybe take a look together with @CREDO23 and decide how to proceed?

I am going to take a look @evereq

**Comment by GloireMutaliko21** [comment]
Btw, @CREDO23, let's dive in a short call tomorrow to make sure all the needed flows are correct. Since we have many people working on similar tasks, we have to make sure we don't duplicate codes and spend much time on the same task. We have to make sure we are working on existing features and improve them instead of do it from scratch. 

Sir @evereq, please confirm that...

CC: @Innocent-Akim

**Comment by evereq** [comment]
> Btw, @CREDO23, let's dive in a short call tomorrow to make sure all the needed flows are correct. Since we have many people working on similar tasks, we have to make sure we don't duplicate codes and spend much time on the same task. We have to make sure we are working on existing features and improve them instead of do it from scratch.
> 
> Sir @evereq, please confirm that...
> 
> CC: @Innocent-Akim

Yes, but better to actually split efforts completely, i.e. have someone to handle fully Daily Plans from now, e.g. @CREDO23 . 
So @Innocent-Akim and @GloireMutaliko21 just give him more info and move to other tasks/projects please.

**Comment by GloireMutaliko21** [comment]
> > Btw, @CREDO23, let's dive in a short call tomorrow to make sure all the needed flows are correct. Since we have many people working on similar tasks, we have to make sure we don't duplicate codes and spend much time on the same task. We have to make sure we are working on existing features and improve them instead of do it from scratch.
> > Sir @evereq, please confirm that...
> > CC: @Innocent-Akim
> 
> Yes, but better to actually split efforts completely, i.e. have someone to handle fully Daily Plans from now, e.g. @CREDO23 . So @Innocent-Akim and @GloireMutaliko21 just give him more info and move to other tasks/projects please.

100 % agree sir @evereq

**Comment by evereq** [comment]
@CREDO23 before you move to next tasks / fixes, please work on this one to merge what makes sense / close PR etc.

**Comment by CREDO23** [comment]
> @CREDO23 before you move to next tasks / fixes, please work on this one to merge what makes sense / close PR etc.

Yes @evereq ! Got it

**Review by CREDO23 — COMMENTED** [review]
@evereq, I have just reviewed this PR, everything here have already been done ! We can close it !

**Pull request closed without merging**
