### PR TITLE
feat: adapt sub-menus of 'Team' & 'Personal' menus UI

### PR DESCRIPTION
**Pull request by land-bit**
## Description

Please include a summary of the changes and the related issue.

I just adapted the sidebar menus of settings so that it is visible as requested in issue #3013 

## Type of Change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Breaking change
-   [ ] Documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings

## Previous screenshots

Please add here videos or images of previous status

On #3013 issue

## Current screenshots

Please add here videos or images of previous status

Capture d’écran du 2024-09-12 16-19-39

### CODE REVIEW

**Comment by Cedric921** [comment]
Please @land-bit can you Sign/Accept the [Contributor License Agreement](https://cla-assistant.io/ever-co/ever-teams?pullRequest=3018)
The Yellow button in the second comment

**Comment by land-bit** [comment]
Capture d’écran du 2024-09-13 08-51-49
I've been trying to do it since yesterday but it doesn't work.

**Comment by Cedric921** [comment]
> Capture d’écran du 2024-09-13 08-51-49 I've been trying to do it since yesterday but it doesn't work.


At the bottom of this page you will see a button `Signin with Github` then you can follow the steps.

**Comment by land-bit** [comment]
I'm already logged in. See the top left corner of the capture.

**Comment by land-bit** [comment]
I've just seen the problem, my git and my gitHub don't use the same user.

So the license has to be signed by two users while the other one doesn't have gitHub, and I'll have to make a new PR to solve this problem.
Capture d’écran du 2024-09-13 10-37-58
Capture d’écran du 2024-09-13 10-49-44

**Pull request closed without merging**
