### PR TITLE
1107 long task title is not looking good

### LINKED ISSUE #1069: BUG: Breadcrumb text/icon alignment should be same in all the pages
Add a `Home` icon on the home page to make it consistent

[Ever-Teams-Breadcrumb.webm](https://github.com/ever-co/ever-teams/assets/81486442/800f685e-78df-424b-bf99-23e81c8d7117)

**Change from:**
image
**to:**
image

### LINKED ISSUE #1088: Task Details Page: Update sidebar background color for Dark mode
**From**
image

**To**
image

### LINKED ISSUE #1089: Reposition Copy Title button
image

### LINKED ISSUE #1091: Remove unnecessary border on opening of dropdown
May be the border is of focus event, but we should not show it

https://github.com/ever-co/ever-teams/assets/81486442/aa31e7f5-083e-4e78-be66-a3b737bc7118

### LINKED ISSUE #1094: Incorrect Alignment/Spacing in Member Task page
### **Current Behaviour**
image

### **Expected Behaviour**
image

### LINKED ISSUE #1102: Improve button size/alignment
### **Current Implementation**
image

### **Expected Implementation**
image

### LINKED ISSUE #1103: Have a fix height to show only 5-6 tasks in child/related issues
- Make the list scrollable

image

### LINKED ISSUE #1106: When Task Title is Long, Task Type badge is not showing
[Ever-Teams-Task-Title-Issue.webm](https://github.com/ever-co/ever-teams/assets/81486442/863e2546-108f-4be3-9cb8-8ed1943fb16b)

image

### LINKED ISSUE #1108: It is not allowing user to set Start Date when Due Date is already set and user try to set Start date with same date
[Ever-Teams-Start-Due-Date-Issue.webm](https://github.com/ever-co/ever-teams/assets/81486442/df6317a4-1875-4b70-bf0e-6ff0095fac4e)

### PR DESCRIPTION
**Pull request by paradoxe35**
- Fix #1091
- Fix #1069
- Fix #1108
- Fix #1106
- Fix #1103
- Fix #1102
- Fix #1094
- Fix #1108
- Fix #1089
- Fix #1088

### CODE REVIEW

**Comment by badalkhatri0924** [comment]
image

image

image

@paradoxe35 There are still some alignment/spacing issues here.

**Comment by badalkhatri0924** [comment]
image

@paradoxe35 There are still some spacing.

**Comment by badalkhatri0924** [comment]
image

image

@paradoxe35 I think better we keep similar type of button UI here

**Comment by evereq** [comment]
@badalkhatri0924 @paradoxe35 guys please fix conflict after @badalkhatri0924  fix it in other PRs

**Comment by badalkhatri0924** [comment]
@paradoxe35 I fixed conflicts, plz take latest pull of this branch to do above changes.

**Comment by evereq** [comment]
I merged another PRs, now this one still conflicts @badalkhatri0924 / @paradoxe35

**Comment by badalkhatri0924** [comment]
> I merged another PRs, now this one still conflicts @badalkhatri0924 / @paradoxe35 

@evereq I'll fix it in sometime.

**Comment by evereq** [comment]
Also, I don't like that "home" icon, looks terrible...

**Comment by badalkhatri0924** [comment]
> Also, I don't like that "home" icon, looks terrible...

What if we remove icons? Home/Back both?

**Comment by evereq** [comment]
@badalkhatri0924 hm, I think showing <- still makes sense so that users understand that there is a way to "exit" back etc.  Let's just find nice looking icons and make it look great

**Comment by evereq** [comment]
@paradoxe35 when you can finialize this? Because as we merging other PRs, it seems we get more and more conflicts for this one... Please next time create many smaller PRs so we merge all faster!

**Comment by paradoxe35** [comment]
@evereq 
Gonna fix these above soon, I'm not near my computer now

**Comment by paradoxe35** [comment]
@evereq 
I think we can merge this, I'm creating a new PR for the above reviews

**Pull request merged**
