### PR TITLE
Fix/updated GitHub integration UI

### PR DESCRIPTION
**Pull request by badalkhatri0924**
image

### CODE REVIEW

**Comment by evereq** [comment]
Hm, but what about text of description for each? Is it "Lorem" like in screenshot!? :)

**Comment by evereq** [comment]
Also, text is "hardcoded" in the components code...

**Comment by evereq** [comment]
@badalkhatri0924 see also https://github.com/ever-co/ever-teams/actions/runs/6815310943/job/18534123124#step:7:50

**Comment by badalkhatri0924** [comment]
@evereq fixed all.

**Pull request merged**
