### PR TITLE
fixed double letter insert and paste issue for android

### PR DESCRIPTION
**Pull request by desperado1802**
#1827

In separate PR going to use the created component in all files code input is required

Android:
https://github.com/ever-co/ever-teams/assets/124465103/726dfd09-1a6d-465d-bde3-b7f17f16b6af

iOS: 
https://github.com/ever-co/ever-teams/assets/124465103/e8b4b828-7479-45b9-a19a-cdd8acd08e25

### CODE REVIEW

**Comment by evereq** [comment]
Hm, can't we find maybe some component for such things??? It looks VERY weird that we have to write such "low-level" functionality ourselves! Maybe there is prebuilt component for accepting such "code" inputs for ReactNative etc. Can you search!?

**Comment by desperado1802** [comment]
> Hm, can't we find maybe some component for such things??? It looks VERY weird that we have to write such "low-level" functionality ourselves! Maybe there is prebuilt component for accepting such "code" inputs for ReactNative etc. Can you search!?

I found this one @evereq https://www.npmjs.com/package/react-native-confirmation-code-field. Should we use it?

**Comment by evereq** [comment]
Yes please @desperado1802

**Comment by desperado1802** [comment]
> @desperado1802 please let me know when we can merge it

Testted on iOS, and Android in emulator. Working fine. We can merge @evereq

**Pull request merged**
