### PR TITLE
Update/make recaptcha optional

### PR DESCRIPTION
**Pull request by maceteligolden**

### CODE REVIEW

**Comment by evereq** [comment]
@maceteligolden it seems we have merge issue, can you resolve it or you need help? If yes, please ask Badal for help in Slack :)

**Comment by maceteligolden** [comment]
@evereq i've resolved the merge conflict

**Comment by badalkhatri0924** [comment]
image

@maceteligolden Why file changes?

**Review by badalkhatri0924 — CHANGES_REQUESTED** [review]
.next is build folder, should not be included in git

**Comment by maceteligolden** [comment]
> .next is build folder, should not be included in git

thanks for pointing that out, removed the folder

**Comment by evereq** [comment]
@badalkhatri0924 please review again and if all good let's merge this :)

**Pull request merged**
