### PR TITLE
Feat/cardOrder:  make cards element (of list view) draggable 

### PR DESCRIPTION
**Pull request by Cedric921**
[screen-recorder-thu-dec-21-2023-23-31-07.webm](https://github.com/ever-co/ever-teams/assets/83704005/8b54c03c-9bfd-4551-b038-0e676a67e517)

### CODE REVIEW

**Comment by maceteligolden** [comment]
@Cedric921 can you use react-beautiful-dnd library to implement the drag and drop feature?

**Comment by Cedric921** [comment]
> @Cedric921 can you use react-beautiful-dnd library to implement the drag and drop feature?

let me check how it work

**Comment by evereq** [comment]
@Cedric921 please resolve merge conflict as we just pushed very large update to develop. Do it carefully to avoid mistakes, talk to Badal if needed

**Comment by evereq** [comment]
@Cedric921 I think we already pushed to production relevant part of API changes in Gauzy, so can you prepare this PR to be merged today?

**Comment by Cedric921** [comment]
> @Cedric921 I think we already pushed to production relevant part of API changes in Gauzy, so can you prepare this PR to be merged today?

Yes sir, this PR will be ready today

**Pull request merged**
