### PR TITLE
fix: Unneccessary Loader

### PR DESCRIPTION
**Pull request by badalkhatri0924**
**BEFORE**
https://github.com/ever-co/ever-teams/assets/81486442/c9e710fb-932e-40f6-ab22-bb2beb2ebcfd

**AFTER**
https://github.com/ever-co/ever-teams/assets/81486442/76f4260e-4d72-4c9e-bb29-123ddbc4b21c

### CODE REVIEW

**Comment by badalkhatri0924** [comment]
@YehualashetGit plz check this PR, after your last PR we started getting this issue.

**Comment by YehualashetGit** [comment]
> @YehualashetGit plz check this PR, after your last PR we started getting this issue.

let me look at it @badalkhatri0924

**Comment by YehualashetGit** [comment]
> > @YehualashetGit plz check this PR, after your last PR we started getting this issue.
> 
> let me look at it @badalkhatri0924

@badalkhatri0924  Please watch the video below; I've checked it and did not notice any extra loading. Please check the network logs from your local machine and let me know if the problem persists on my local machine only.
https://www.veed.io/view/ef497512-a762-435c-a128-9e98c3bb4fd8?panel=share

**Comment by YehualashetGit** [comment]
> > > > @YehualashetGit, please check this PR; after your last PR, we started getting this issue.
> > > 
> > > 
> > > let me look at it, @badalkhatri0924
> > 
> > 
> > @badalkhatri0924 Please watch the video below; I've checked it and did not notice any extra loading. Please check the network logs from your local machine and let me know if the problem persists on my local machine only. https://www.veed.io/view/ef497512-a762-435c-a128-9e98c3bb4fd8?panel=share
> 
> @YehualashetGit I am not getting anything from the video.

Perhaps my explanation was not clear enough, but I would like to know why there are so many needless network requests.
@badalkhatri0924

**Comment by evereq** [comment]
@YehualashetGit please listen to your own video https://www.veed.io/view/ef497512-a762-435c-a128-9e98c3bb4fd8?panel=share, I think it does not have your voice and instead some radio or Youtube, that's reason why @badalkhatri0924 can't understand anything. It also show low resolution everything etc. I would suggest to use something like Loom or other tools that record good videos without issues...

**Pull request merged**
