### PR TITLE
Feat/add kanban board

### PR DESCRIPTION
**Pull request by maceteligolden**
https://www.loom.com/share/485b847edf2e4cf0a199af3a7199c723?sid=76e5ccda-7264-439d-adf9-b099b8969f09

### CODE REVIEW

**Comment by evereq** [comment]
@maceteligolden not sure if it's in your code or it's some other code, but DeepScan found 14 "new" issues, can you check / fix those please? Thanks!

**Comment by evereq** [comment]
@maceteligolden I think we also having Lint issues, please check errors in https://github.com/ever-co/ever-teams/actions/runs/6973212404/job/18976803726?pr=1861#step:7:24

**Comment by maceteligolden** [comment]
Noted @evereq i'll attend to the issues

**Comment by maceteligolden** [comment]
@evereq i have resolved the issues

**Comment by maceteligolden** [comment]
@evereq i have a fixed the issues

**Comment by evereq** [comment]
Great, one more - https://github.com/ever-co/ever-teams/actions/runs/6979678789/job/18993412819?pr=1861#step:3:14 - you need to add those words to .cspell file or fix typos etc.

**Comment by maceteligolden** [comment]
@evereq alright, i'm working on that now

**Comment by maceteligolden** [comment]
@evereq i have worked on the check spelling error. i can't see why Codacy static code analysis is failing

**Pull request merged**
