### PR TITLE
added defaultTeamId to be saved in asyncStorage

### PR DESCRIPTION
**Pull request by desperado1802**
#1828

User 1's first Login:
https://github.com/ever-co/ever-teams/assets/124465103/fe745bbb-c3ff-47aa-91a3-1eca04bddba1

User 1's second login, default team is selected auto:
https://github.com/ever-co/ever-teams/assets/124465103/d5d53a9c-09e6-44fa-a71f-4ac7b8baa9b0

After that User 2 tries to login, and there is no record for him in localStorage for that reason first team is selected by default:
https://github.com/ever-co/ever-teams/assets/124465103/28d09925-eb3b-4557-a547-d2df9816fad9

### CODE REVIEW

**Comment by evereq** [comment]
This waiting for @rahul-rocket to add userId in auth response so we can use userId in this flow

**Comment by rahul-rocket** [comment]
> This waiting for @rahul-rocket to add userId in auth response so we can use userId in this flow

@evereq @badalkhatri0924 @desperado1802 I have added userId inside existing API and code are already merged into develop branch.

**Comment by evereq** [comment]
@desperado1802 can you please resolve conflicts? Thanks!

**Comment by desperado1802** [comment]
> @desperado1802 can you please resolve conflicts? Thanks!

Conflicts are resolved @evereq

**Comment by evereq** [comment]
@desperado1802 merged with squash, don't use this branch anymore, thanks!

**Pull request merged**
