### PR TITLE
Improve/task title epic

### PR DESCRIPTION
**Pull request by desperado1802**
#1669

Added the add/change parent and block showing parent number and name

https://github.com/ever-co/ever-teams/assets/124465103/67d4f969-cb7f-4d3c-9c57-2bcf67b298aa

File

### CODE REVIEW

**Review by badalkhatri0924 — CHANGES_REQUESTED** [review]
@desperado1802 Looks like font size is not proper.

image
image

**Comment by badalkhatri0924** [comment]
image
@desperado1802

**Comment by desperado1802** [comment]
> @desperado1802 Looks like font size is not proper.
> 
> image image

Current:
image

**Comment by desperado1802** [comment]
> image @desperado1802


https://github.com/ever-co/ever-teams/assets/124465103/90312d14-bd4f-490f-afac-b4f19fde1a0c

**Pull request merged**
