### PR TITLE
refactor: Estimate | '0' hours should display in different way

### LINKED ISSUE #2767: [Improvement] Estimate | '0' hours should display in different way
The issue is that when the user provides an estimate of less than 1 hour, the estimate time section does not look nice (under the main card)

Variants:

- Display only 'Minutes' if there are '0' hours
- Display '0' hours without lines below
- Display empty section without lines below

**Important**: lines below should exist ONLY if BOTH inputs Hours & Minutes are empty, when ONE of them is filled, another one should NOT have the lines.

Screenshot at Jul 19 10-11-13

 @evereq please provide your vision which variant is more preferable

### PR DESCRIPTION
**Pull request by CREDO23**
### This PR intends to fix #2767 

@evereq, @KostyaEver, please check what I did [here](https://www.loom.com/share/cf4bf21114d847969d043d92dd3b3b5a?sid=bf85be38-3950-4cf7-8dd1-3da308fc6996)

### CODE REVIEW

**Comment by evereq** [comment]
@CREDO23 it's still not perfect UX... why for example loading indicators replaces minutes text "m" and not displayed near to it? And so on, there are at least few issues with this still present....

**Comment by CREDO23** [comment]
Ok @evereq , let me improve it

**Comment by CREDO23** [comment]
@evereq @KostyaEver 
What about this one ? [Loom](https://www.loom.com/share/795bfc7d37cc4ab3a720d1b85e222b49?sid=1fb2fe28-3cf6-43f1-b035-f77fafe664d6)

**Review by Cedric921 — APPROVED** [review]

**Comment by evereq** [comment]
Interesting how hard for devs to build the most basic things... e.g. center text in the button, you can google was nice post about it... Anyway, this is still not perfect, for example the text is not aligned well or the loading indicator padding sometimes bigger, sometimes smaller (I.e it stay on the same place all time, but it should be close to value it saving..... it's like you can't make all of it well at the same time... many will probably give up and just keep show 00m if user did not enter value for minutes and same for hours keep using 00h if user did not enter hours, but entered minutes etc. I am not suggesting to do that, but I am saying if you can't make it all work well, that might be a good way to resolve tons of issues....... @CREDO23 
@Cedric921 do you like fully how it work now? Did not notice any issues? Interesting...

**Comment by CREDO23** [comment]
Thanks for your feedbacks @evereq. Let me give another try!

**Comment by CREDO23** [comment]
Please, check this out [Loom](https://www.loom.com/share/f4dbb7a334124db2b9fa3766b6c0aa58?sid=b42df74f-3e17-4bc3-a999-59b230840474)  
@evereq

**Pull request merged**
