### PR TITLE
3008 improvements see plan  user should be able to see all plans on the calendar

### LINKED ISSUE #3008: [Improvements] 'See Plan' | User should be able to see all plans on the Calendar
The issue is that the user can not see all plans in the tab 'Future', when Today and Tomorrow exist

**Expect**: in tab 'Future' the Calendar should display all dates with plans, but if clicking on dates 'Today' or 'Tomorrow' will be redirected to the same tabs 'Today' and 'Tomorrow'.

Screenshot at Sep 10 10-03-23

ONE more improvement that 'Past' plans also should be able to see, but Dates in the calendar should be marked a bit differently so that users can understand where are the past where are the future . (maybe 'White' dots)

### PR DESCRIPTION
**Pull request by CREDO23**
## Description

This PR fixes #3008 

## Type of Change

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change
-   [ ] Documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings

## Current screenshots

[Loom](https://www.loom.com/share/e8da9f0671f04318abf71d8885eea22a)

### CODE REVIEW

**Review by Cedric921 — COMMENTED** [review]
Many changes have already been made in the previous PR, see this file
https://github.com/ever-co/ever-teams/pull/3015/files

**Comment by CREDO23** [comment]
Yeah @Cedric921 !
This PR is on top of #3015

**Comment by evereq** [comment]
@CREDO23 so can you rebase and fix merge conflict please?

**Comment by CREDO23** [comment]
sure @evereq

**Pull request merged**
