### PR TITLE
Fix/add package issue

### PR DESCRIPTION
**Pull request by maceteligolden**

### CODE REVIEW

**Comment by YehualashetGit** [comment]
@maceteligolden  At the moment, our current workaround for installing a new package involves manually adding the package to the `package.json` file and then running `yarn install`. We would like to learn about your recommended solution along with the corresponding command to execute

**Comment by maceteligolden** [comment]
@YehualashetGit  in this PR i have been able to enable installation using 
`yarn add package-name`
My solution involved setting a yarn policy for the application

**Comment by YehualashetGit** [comment]
> @YehualashetGit in this PR i have been able to enable installation using `yarn add package-name` My solution involved setting a yarn policy for the application

Great, I can help with testing by checking out  to your branch.

**Comment by maceteligolden** [comment]
@YehualashetGit alright, please let me know how it goes

**Comment by evereq** [comment]
@maceteligolden please accept CAA agreement by clicking button in the comment https://github.com/ever-co/ever-teams/pull/1633#issuecomment-1777011836

**Comment by YehualashetGit** [comment]
> @YehualashetGit alright, please let me know how it goes

@maceteligolden yes I've tested, and now we can install new package without any issue

**Comment by evereq** [comment]
OK, @maceteligolden did you checked if update to NX / Lerna can solve this issue without need to add Yarn policy?

**Comment by maceteligolden** [comment]
@evereq i was able to upgrade nx and lerna to the latest versions. it didn't resolve the issue

**Pull request merged**
