### PR TITLE
[Feature] Add manual time popup page 

### PR DESCRIPTION
**Pull request by GedeonTS**
[

https://github.com/user-attachments/assets/26ab4b55-5cc5-47ec-b5a9-339adec500f8

](url)

### CODE REVIEW

**Comment by Cedric921** [comment]
Is it possible to attach a video showing how it works?
@GedeonTS

**Review by Cedric921 — CHANGES_REQUESTED** [review]
I just put the PR in draft while you finish the updates I proposed in Slack
@GedeonTS 
CC: @evereq

**Comment by evereq** [comment]
@GedeonTS fix merge conflict please. If need help, ask @GloireMutaliko21

**Comment by evereq** [comment]
@GedeonTS I don't get it, why you added https://github.com/catc/react-timekeeper package!? It's not supported for 3+ years!

**Comment by GedeonTS** [comment]
Hi @evereq , @Cedric921  I have fixed the conflict and also removed the TimeKeeper package.

**Pull request merged**
